name: sub_app
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  subtitle: ^0.1.0-beta.3
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  media_store_plus: ^0.1.3
  realm: ^20.0.0
  equatable: ^2.0.7
  get_it: ^8.0.2
  bloc: ^8.1.4
  image_picker: ^1.1.2
  flutter_context_menu: ^0.2.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  rename: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

