// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnD8hJ7O818WcAgN2cPkcoCKsF1yEPZrA',
    appId: '1:765746702344:web:7155762c8a06d03f0089bd',
    messagingSenderId: '765746702344',
    projectId: 'subapp-82d42',
    authDomain: 'subapp-82d42.firebaseapp.com',
    storageBucket: 'subapp-82d42.firebasestorage.app',
    measurementId: 'G-TNG181XHM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDHaVEhPwABinQ3PCnjn9yCrUXCBWtp8',
    appId: '1:765746702344:android:e3beaebb606cc2180089bd',
    messagingSenderId: '765746702344',
    projectId: 'subapp-82d42',
    storageBucket: 'subapp-82d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-mWDr-s4aS3il_KXAsU55cYfIllpf84',
    appId: '1:765746702344:ios:60bad5398d8f8ebd0089bd',
    messagingSenderId: '765746702344',
    projectId: 'subapp-82d42',
    storageBucket: 'subapp-82d42.firebasestorage.app',
    iosBundleId: 'com.example.subApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-mWDr-s4aS3il_KXAsU55cYfIllpf84',
    appId: '1:765746702344:ios:60bad5398d8f8ebd0089bd',
    messagingSenderId: '765746702344',
    projectId: 'subapp-82d42',
    storageBucket: 'subapp-82d42.firebasestorage.app',
    iosBundleId: 'com.example.subApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnD8hJ7O818WcAgN2cPkcoCKsF1yEPZrA',
    appId: '1:765746702344:web:2976d27609e87d120089bd',
    messagingSenderId: '765746702344',
    projectId: 'subapp-82d42',
    authDomain: 'subapp-82d42.firebaseapp.com',
    storageBucket: 'subapp-82d42.firebasestorage.app',
    measurementId: 'G-0VRSYDCSYC',
  );
}
